---


- hosts: all

  tasks:

  - name: install collectd
    become: yes
    become_user: root
    package: name=collectd state=latest

  - name: copy collectd.conf for ubuntu
    when: ansible_pkg_mgr == "apt"
    become: yes
    become_user: root
    copy:
      src: ../files/collectd.conf
      dest: /etc/collectd/collectd.conf

  - name: collectd.conf for RHEL
    when: ansible_pkg_mgr == "yum"
    become: yes
    become_user: root
    copy:
      src: ../files/collectdyum.conf
      dest: /etc/collectd.conf

  - name : restart collectd
    become: yes
    become_user: root
    command: /etc/init.d/collectd restart
